"""empty message

Revision ID: 39a552eb65ac
Revises: 97919189dec9
Create Date: 2022-01-05 23:39:09.012309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a552eb65ac'
down_revision = '97919189dec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('image_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'directory', 'image', ['image_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directory', type_='foreignkey')
    op.drop_column('directory', 'image_id')
    # ### end Alembic commands ###
