"""empty message

Revision ID: 675a43a678a8
Revises: 84174a640dd0
Create Date: 2021-12-30 23:59:35.743137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '675a43a678a8'
down_revision = '84174a640dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('directory', 'last_scan')
    op.drop_column('library', 'last_scan')
    op.drop_column('media', 'last_scan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('last_scan', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('last_scan', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('directory', sa.Column('last_scan', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'notes')
    op.drop_column('album', 'notes')
    # ### end Alembic commands ###
