"""empty message

Revision ID: 7f42ca79825b
Revises: 8f27a15d7daa
Create Date: 2025-03-16 16:39:54.751141

"""
from pathlib import Path

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f42ca79825b'
down_revision = '8f27a15d7daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directory', sa.Column('name', sa.String()))
    # ### end Alembic commands ###

    conn = op.get_bind()
    for item in conn.execute(sa.text("select id, path from directory")):
        query = sa.text("update directory set name=:name where id=:id")
        conn.execute(query, {
            "id": item[0],
            "name": Path(item[1]).name,
        })

    op.alter_column("directory", "name", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directory', 'name')
    # ### end Alembic commands ###
