"""empty message

Revision ID: 857418f3e731
Revises: a8f35f30a12c
Create Date: 2022-01-11 18:04:40.715492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857418f3e731'
down_revision = 'a8f35f30a12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('mimetype', sa.String(), nullable=True))
    op.add_column('image', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'width')
    op.drop_column('image', 'height')
    op.drop_column('image', 'mimetype')
    # ### end Alembic commands ###
