"""empty message

Revision ID: 8f27a15d7daa
Revises: 
Create Date: 2025-03-15 16:40:29.304789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f27a15d7daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=False)
    op.create_table('image',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('artist',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('music_brainz_id', sa.String(), nullable=True),
    sa.Column('last_fm_url', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('scanned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.create_table('directory',
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['directory.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_path'), 'directory', ['path'], unique=False)
    op.create_table('user_library',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    op.create_table('album',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('music_brainz_id', sa.String(), nullable=True),
    sa.Column('last_fm_url', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('scanned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_name'), 'album', ['name'], unique=False)
    op.create_table('starred_artist',
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starred_artist_artist_id'), 'starred_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_starred_artist_user_id'), 'starred_artist', ['user_id'], unique=False)
    op.create_table('starred_directory',
    sa.Column('directory_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directory.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starred_directory_directory_id'), 'starred_directory', ['directory_id'], unique=False)
    op.create_index(op.f('ix_starred_directory_user_id'), 'starred_directory', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=True),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('image_id', sa.String(), nullable=True),
    sa.Column('scanned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='set null'),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['parent_id'], ['directory.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_path'), 'media', ['path'], unique=False)
    op.create_table('starred_album',
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starred_album_album_id'), 'starred_album', ['album_id'], unique=False)
    op.create_index(op.f('ix_starred_album_user_id'), 'starred_album', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('media_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_media_id'), 'history', ['media_id'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('media_genre',
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_table('starred_media',
    sa.Column('media_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starred_media_media_id'), 'starred_media', ['media_id'], unique=False)
    op.create_index(op.f('ix_starred_media_user_id'), 'starred_media', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_starred_media_user_id'), table_name='starred_media')
    op.drop_index(op.f('ix_starred_media_media_id'), table_name='starred_media')
    op.drop_table('starred_media')
    op.drop_table('media_genre')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_media_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_starred_album_user_id'), table_name='starred_album')
    op.drop_index(op.f('ix_starred_album_album_id'), table_name='starred_album')
    op.drop_table('starred_album')
    op.drop_index(op.f('ix_media_path'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_starred_directory_user_id'), table_name='starred_directory')
    op.drop_index(op.f('ix_starred_directory_directory_id'), table_name='starred_directory')
    op.drop_table('starred_directory')
    op.drop_index(op.f('ix_starred_artist_user_id'), table_name='starred_artist')
    op.drop_index(op.f('ix_starred_artist_artist_id'), table_name='starred_artist')
    op.drop_table('starred_artist')
    op.drop_index(op.f('ix_album_name'), table_name='album')
    op.drop_table('album')
    op.drop_table('user_library')
    op.drop_index(op.f('ix_directory_path'), table_name='directory')
    op.drop_table('directory')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_table('artist')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('library')
    op.drop_table('image')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
