"""empty message

Revision ID: 8fd2f5658acd
Revises: 7f42ca79825b
Create Date: 2025-03-16 21:35:40.993061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd2f5658acd'
down_revision = '7f42ca79825b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_index(op.f('ix_client_user_id'), 'client', ['user_id'], unique=False)
    op.add_column('history', sa.Column('now_playing', sa.Boolean(), nullable=True))
    op.add_column('history', sa.Column('client_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_history_client_id'), 'history', ['client_id'], unique=False)
    op.create_index(op.f('ix_history_now_playing'), 'history', ['now_playing'], unique=False)
    op.create_foreign_key(None, 'history', 'client', ['client_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_index(op.f('ix_history_now_playing'), table_name='history')
    op.drop_index(op.f('ix_history_client_id'), table_name='history')
    op.drop_column('history', 'client_id')
    op.drop_column('history', 'now_playing')
    op.drop_index(op.f('ix_client_user_id'), table_name='client')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
