"""empty message

Revision ID: 99bca8998b42
Revises: 8a37891f29aa
Create Date: 2021-12-28 17:30:50.549672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bca8998b42'
down_revision = '8a37891f29aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=False)
    op.create_table('album',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_name'), 'album', ['name'], unique=False)
    op.create_table('media_genre',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.add_column('media', sa.Column('title', sa.String(), nullable=True))
    op.add_column('media', sa.Column('duration', sa.Numeric(), nullable=True))
    op.add_column('media', sa.Column('bitrate', sa.Numeric(), nullable=True))
    op.add_column('media', sa.Column('size', sa.Numeric(), nullable=True))
    op.add_column('media', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('media', sa.Column('is_video', sa.Boolean(), nullable=True))
    op.add_column('media', sa.Column('album_id', sa.String(), nullable=True))
    op.add_column('media', sa.Column('artist_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'media', 'artist', ['artist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'media', 'album', ['album_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'artist_id')
    op.drop_column('media', 'album_id')
    op.drop_column('media', 'is_video')
    op.drop_column('media', 'content_type')
    op.drop_column('media', 'size')
    op.drop_column('media', 'bitrate')
    op.drop_column('media', 'duration')
    op.drop_column('media', 'title')
    op.drop_table('media_genre')
    op.drop_index(op.f('ix_album_name'), table_name='album')
    op.drop_table('album')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
