"""empty message

Revision ID: 9df50f0ddc90
Revises: 8fd2f5658acd
Create Date: 2025-03-18 17:33:15.790339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df50f0ddc90'
down_revision = '8fd2f5658acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_rating',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directory.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_directory_rating_directory_id', 'directory_rating', ['directory_id'], unique=False)
    op.create_index('ix_directory_rating_directory_id_user_id', 'directory_rating', ['directory_id', 'user_id'], unique=True)
    op.create_index('ix_directory_rating_user_id', 'directory_rating', ['user_id'], unique=False)
    op.create_table('media_rating',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_rating_media_id', 'media_rating', ['media_id'], unique=False)
    op.create_index('ix_media_rating_media_id_user_id', 'media_rating', ['media_id', 'user_id'], unique=True)
    op.create_index('ix_media_rating_user_id', 'media_rating', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_rating_user_id', table_name='media_rating')
    op.drop_index('ix_media_rating_media_id_user_id', table_name='media_rating')
    op.drop_index('ix_media_rating_media_id', table_name='media_rating')
    op.drop_table('media_rating')
    op.drop_index('ix_directory_rating_user_id', table_name='directory_rating')
    op.drop_index('ix_directory_rating_directory_id_user_id', table_name='directory_rating')
    op.drop_index('ix_directory_rating_directory_id', table_name='directory_rating')
    op.drop_table('directory_rating')
    # ### end Alembic commands ###
