"""empty message

Revision ID: b5ddf68226dd
Revises: 9df50f0ddc90
Create Date: 2025-03-26 17:24:09.612301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5ddf68226dd'
down_revision = '9df50f0ddc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_album_name', table_name='album')
    op.create_index(op.f('ix_album_artist_id'), 'album', ['artist_id'], unique=False)
    op.create_index(op.f('ix_album_image_id'), 'album', ['image_id'], unique=False)
    op.create_index('ix_album_name_year_artist_id', 'album', ['name', 'year', 'artist_id'], unique=True)
    op.alter_column('artist', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_artist_image_id'), 'artist', ['image_id'], unique=False)
    op.drop_index('ix_client_name', table_name='client')
    op.create_index('ix_client_name_user_id', 'client', ['name', 'user_id'], unique=True)
    op.alter_column('directory', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_directory_path', table_name='directory')
    op.create_index(op.f('ix_directory_image_id'), 'directory', ['image_id'], unique=False)
    op.create_index(op.f('ix_directory_last_seen'), 'directory', ['last_seen'], unique=False)
    op.create_index(op.f('ix_directory_library_id'), 'directory', ['library_id'], unique=False)
    op.create_index('ix_directory_library_id_path', 'directory', ['library_id', 'path'], unique=True)
    op.create_index(op.f('ix_directory_parent_id'), 'directory', ['parent_id'], unique=False)
    op.create_unique_constraint('uq_directory_path', 'directory', ['path'])
    op.alter_column('history', 'now_playing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('history', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('history', 'media_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_history_now_playing', table_name='history')
    op.alter_column('image', 'mimetype',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('image', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('image', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_image_path', 'image', ['path'])
    op.create_unique_constraint('uq_library_name', 'library', ['name'])
    op.alter_column('media', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('media', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('media', 'parent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_media_path', table_name='media')
    op.create_index(op.f('ix_media_album_id'), 'media', ['album_id'], unique=False)
    op.create_index(op.f('ix_media_artist_id'), 'media', ['artist_id'], unique=False)
    op.create_index('ix_media_id_library_id', 'media', ['id', 'library_id'], unique=True)
    op.create_index(op.f('ix_media_image_id'), 'media', ['image_id'], unique=False)
    op.create_index(op.f('ix_media_last_seen'), 'media', ['last_seen'], unique=False)
    op.create_index(op.f('ix_media_library_id'), 'media', ['library_id'], unique=False)
    op.create_index('ix_media_library_id_path', 'media', ['library_id', 'path'], unique=True)
    op.create_index(op.f('ix_media_parent_id'), 'media', ['parent_id'], unique=False)
    op.create_unique_constraint('uq_media_path', 'media', ['path'])
    op.alter_column('starred_album', 'album_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_starred_album_album_id_user_id', 'starred_album', ['album_id', 'user_id'], unique=True)
    op.alter_column('starred_artist', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_starred_artist_artist_id_user_id', 'starred_artist', ['artist_id', 'user_id'], unique=True)
    op.alter_column('starred_directory', 'directory_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_starred_directory_directory_id_user_id', 'starred_directory', ['directory_id', 'user_id'], unique=True)
    op.alter_column('starred_media', 'media_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_starred_media_media_id_user_id', 'starred_media', ['media_id', 'user_id'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index('ix_starred_media_media_id_user_id', table_name='starred_media')
    op.alter_column('starred_media', 'media_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_starred_directory_directory_id_user_id', table_name='starred_directory')
    op.alter_column('starred_directory', 'directory_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_starred_artist_artist_id_user_id', table_name='starred_artist')
    op.alter_column('starred_artist', 'artist_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_starred_album_album_id_user_id', table_name='starred_album')
    op.alter_column('starred_album', 'album_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_media_path', 'media', type_='unique')
    op.drop_index(op.f('ix_media_parent_id'), table_name='media')
    op.drop_index('ix_media_library_id_path', table_name='media')
    op.drop_index(op.f('ix_media_library_id'), table_name='media')
    op.drop_index(op.f('ix_media_last_seen'), table_name='media')
    op.drop_index(op.f('ix_media_image_id'), table_name='media')
    op.drop_index('ix_media_id_library_id', table_name='media')
    op.drop_index(op.f('ix_media_artist_id'), table_name='media')
    op.drop_index(op.f('ix_media_album_id'), table_name='media')
    op.create_index('ix_media_path', 'media', ['path'], unique=False)
    op.alter_column('media', 'parent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('media', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('media', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('uq_library_name', 'library', type_='unique')
    op.drop_constraint('uq_image_path', 'image', type_='unique')
    op.alter_column('image', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('image', 'mimetype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_history_now_playing', 'history', ['now_playing'], unique=False)
    op.alter_column('history', 'media_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('history', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('history', 'now_playing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('uq_directory_path', 'directory', type_='unique')
    op.drop_index(op.f('ix_directory_parent_id'), table_name='directory')
    op.drop_index('ix_directory_library_id_path', table_name='directory')
    op.drop_index(op.f('ix_directory_library_id'), table_name='directory')
    op.drop_index(op.f('ix_directory_last_seen'), table_name='directory')
    op.drop_index(op.f('ix_directory_image_id'), table_name='directory')
    op.create_index('ix_directory_path', 'directory', ['path'], unique=False)
    op.alter_column('directory', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_client_name_user_id', table_name='client')
    op.create_index('ix_client_name', 'client', ['name'], unique=False)
    op.drop_index(op.f('ix_artist_image_id'), table_name='artist')
    op.alter_column('artist', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_album_name_year_artist_id', table_name='album')
    op.drop_index(op.f('ix_album_image_id'), table_name='album')
    op.drop_index(op.f('ix_album_artist_id'), table_name='album')
    op.create_index('ix_album_name', 'album', ['name'], unique=False)
    op.alter_column('album', 'scanned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
