"""empty message

Revision ID: c4acf3fc4b8c
Revises: 857418f3e731
Create Date: 2022-05-14 00:06:06.025427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4acf3fc4b8c'
down_revision = '857418f3e731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('last_fm_url', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('last_fm_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'last_fm_url')
    op.drop_column('album', 'last_fm_url')
    # ### end Alembic commands ###
