"""empty message

Revision ID: d678b690a5d9
Revises: 99bca8998b42
Create Date: 2021-12-29 18:44:09.274311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd678b690a5d9'
down_revision = '99bca8998b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('album', sa.Column('music_brainz_id', sa.String(), nullable=True))
    op.add_column('album', sa.Column('image_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'album', 'image', ['image_id'], ['id'], ondelete='set null')
    op.add_column('artist', sa.Column('music_brainz_id', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('image_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'artist', 'image', ['image_id'], ['id'], ondelete='set null')
    op.add_column('media', sa.Column('year', sa.Numeric(), nullable=True))
    op.add_column('media', sa.Column('track', sa.Numeric(), nullable=True))
    op.add_column('media', sa.Column('image_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'media', 'image', ['image_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'image_id')
    op.drop_column('media', 'track')
    op.drop_column('media', 'year')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'image_id')
    op.drop_column('artist', 'music_brainz_id')
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'image_id')
    op.drop_column('album', 'music_brainz_id')
    op.drop_table('image')
    # ### end Alembic commands ###
