### Used to test connectivity with the server. Takes no extra parameters.
POST {{ domain }}/rest/ping.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}


### Returns all configured top-level music folders.
POST {{ domain }}/rest/getMusicFolders.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}


### Returns an indexed structure of all artists.
POST {{ domain }}/rest/getIndexes.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}


### Returns a listing of all files in a music directory. Typically used
### to get list of albums for an artist, or list of songs for an album.
POST {{ domain }}/rest/getMusicDirectory.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=f404f9ef-3dc8-4096-9ec3-bfa4ba7b19c6


### Returns all genres.
POST {{ domain }}/rest/getGenres.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}


### Similar to getIndexes, but organizes music according to ID3 tags.
POST {{ domain }}/rest/getArtists.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}


### Returns details for an artist, including a list of albums. This method
### organizes music according to ID3 tags.
POST {{ domain }}/rest/getArtist.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=a251bbf5-d469-48d3-b703-5dbe6f7d82b1


### Returns details for an album, including a list of songs. This method
### organizes music according to ID3 tags.
POST {{ domain }}/rest/getAlbum.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=004cd7ef-0f02-4e80-bbe8-a4306f45c47d


### Returns details for a song.
POST {{ domain }}/rest/getSong.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=04dda38d-d820-43c1-ac06-97620b466f30


### Returns random songs matching the given criteria.
POST {{ domain }}/rest/getRandomSongs.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&genre=Soul


### Returns songs in a given genre.
POST {{ domain }}/rest/getSongsByGenre.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&genre=Hard Rock&count=5&offset=0


### Streams a given media file.
POST {{ domain }}/rest/stream.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=09c94a9d-5ad3-4a62-90d3-4e62434b0f4d


### Downloads a given media file. Similar to stream, but this method returns
### the original media data without transcoding or downsampling.
POST {{ domain }}/rest/download.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=09c94a9d-5ad3-4a62-90d3-4e62434b0f4d


### Returns a cover art image.
POST {{ domain }}/rest/getCoverArt.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&id=16bea9f5-735c-425c-b976-65fe65c7ad85


### Get details about a given user, including which authorization roles and
### folder access it has. Can be used to enable/disable certain features in
### the client, such as jukebox control.
POST {{ domain }}/rest/getUser.view
Content-Type: application/x-www-form-urlencoded

{{ req_params }}&username={{ user }}


###

GET http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&api_key=c37f84152757a79c336a3dc49c0e6e3f&mbid=66c662b6-6e2f-4930-8610-912e24c63ed1&format=json
